### ISSUE TITLE
Support for Manta M8P v2.0

### ISSUE THREAD

**Issue by riksarchen** [Rat-Rig/V-CoreOS#105]
### Is your feature request related to a problem? Please describe

Is RatOS gonna support the new upgraded Manta M8P v2.0?

### Describe the solution you'd like

Please add support

**Comment by Twdiap** [comment]
Yay, been trying to setup Ratos since 2 weeks but no luck :(
BTT is not helpful tho...

**Comment by trudeau87** [comment]
Still waitin on 2.0 support........:-(

**Comment by miklschmidt** [comment]
2.0 support is coming in RatOS v2.1 (already implemented [in Rat-OS/RatOS-configuration@development](https://github.com/Rat-OS/RatOS-configuration/commit/2f364bc0892309c8cf2dd84a515a79afc397d668))

**Comment by LivioB74** [comment]
Hi !
Are two week that i try to use my new printer (ratrig vcore3.1 500) but i feel idiot ... especially installing RatOS. Manta M8P v2.0 is not present, so i have tried to configure in many many ways...
I've buy my printer in December, and after mount, check square, find cutted panel, and so on i'm again without print. With klipper i'm a newbye, Ok, but ...
Someone can help me to start working my printer ? I'm starting to go out of mind :( !
Thanks in advance to All.

**Comment by miklschmidt** [comment]
Closed following 2.1.0-RC1

@LivioB74 sorry i didn't see your comment, give https://github.com/Rat-OS/RatOS/releases/tag/v2.1.0-RC1 a shot
