### ISSUE TITLE
LDO Orbiter V2.0 - Configs deviate from OEM suggestions

### ISSUE THREAD

**Issue by swilkens** [Rat-Rig/V-CoreOS#109]
### Is your feature request related to a problem? Please describe

The TMC drivers settings and run current for the LDO Orbiter 2.0 with the LDO-36STH20-1004AHG motor deviate from LDO's specification. This has been done intentionally, but that isn't clear from the configuration files or the documentation.

LDO Suggestions:
![image](https://github.com/Rat-OS/RatOS/assets/13329383/96aa4612-7ac5-4501-a204-4abb879eb9eb)

RatOS settings:
![image](https://github.com/Rat-OS/RatOS/assets/13329383/04622c37-d6a2-4a5a-b139-a845cd28f173)
![image](https://github.com/Rat-OS/RatOS/assets/13329383/c07ea55d-9406-4241-a990-d1b7ed2103d7)

### Describe the solution you'd like

Add a note to the configuration file for the Orbiter v2.0 that clarifies that these changes are by design.

### Additional information

As discussed on Discord with @miklschmidt

**Comment by HelgeKeck** [comment]
run current 0.85 is waya too high and absolutely not needed for a v-core
mikl did this for reasons

**Comment by swilkens** [comment]
Like I said in the issue report, this just serves as a reminder for mikl to make a note in the config file or something :)

**Comment by miklschmidt** [comment]
Yeah basically my explanation here: https://discord.com/channels/582187371529764864/1092127173223125163/1171965371004231730

Should make it into comments or docs somewhere.

**Comment by miklschmidt** [comment]
As 2.1 handles current and presets quite differently, this should be more self explanatory. The configurator will warn about overcurrenting if current is set beyond the rated current of the stepper. It also make it much easier to change, should the user want to try overcurrenting as per OEM suggestions anyway.

**Comment by miklschmidt** [comment]
Closed following 2.1.0-RC1
