### ISSUE TITLE
Active Wifi Lookup during Hotspot mode

### ISSUE THREAD

**Issue by manueldrama** [Rat-Rig/V-CoreOS#111]
### Is your feature request related to a problem? Please describe

When Systems on hotspot mode and connecting by ethernet, from klipperscreen network menu it is impossible to see wifi network to connect. 

### Describe the solution you'd like

Solution can be a option button open hotspot mode and close

**Comment by miklschmidt** [comment]
KlipperScreen chose to drop support for everything but NetworkManager, so the klipperscreen network panel will be disabled in the future. Closing this, use the hotspot and the configurator to configure wifi as outlined in the installation instructions.
