### ISSUE TITLE
ratos cb1, install Happy Hare (ercf manager tool) issue

### ISSUE THREAD

**Issue by Wolffy00** [Rat-Rig/V-CoreOS#112]
### What happened

instal process copy Happy Hare v2(HH) to home/biqu 
"cd ~
git clone https://github.com/moggieuk/Happy-Hare.git
cd Happy-Hare"
then second command is
"./install.sh -i"
![hh1](https://github.com/Rat-OS/RatOS/assets/103823401/1f62ad15-abb6-4bd5-8e10-1301682360e1)
![hh2](https://github.com/Rat-OS/RatOS/assets/103823401/ad97a4be-16d1-4d7f-b538-d6c3c40dd9e3)
![hh3](https://github.com/Rat-OS/RatOS/assets/103823401/3e6b293d-1e21-4e91-9192-7bb27b65ea96)
![hh4](https://github.com/Rat-OS/RatOS/assets/103823401/f224f689-6f12-45a0-a115-fb45f7f690ee)
![hh5](https://github.com/Rat-OS/RatOS/assets/103823401/e250f810-a31a-492b-9be9-a3538d506cdf)

### What did you expect to happen

install in home/pi instead of home/biqu

### How to reproduce

follow original instal process 
https://github.com/moggieuk/Happy-Hare

**Comment by HelgeKeck** [comment]
besides that this is the wrong repo to file a issue, your screenshot already tells you what to do
![image](https://github.com/Rat-OS/RatOS/assets/13624572/3491af65-9866-43e6-bbca-cfb124be193c)
