### ISSUE TITLE
update error with klipper(v0.11.0-219 > v0.12.0-40) and moonraker  (v0.8.0-48 > v0.8.0-231)

### ISSUE THREAD

**Issue by DarkRabbit19** [Rat-Rig/V-CoreOS#114]
### What happened

After the data has been fetched for klipper and/or moonraker. The update fails with the error:  "reference broken".
(this happend on a clean installation).
[Update_log.txt](https://github.com/Rat-OS/RatOS/files/13792080/Update_log.txt)

### What did you expect to happen

That after the update, klipper and moonraker would be the latest version.

### How to reproduce

Clean install on the "Raspberry Pi 3 B" and then in the "MACHINE" tab "update al components".

**Comment by DarkRabbit19** [comment]
problem was fixed with a other re instal of the RATOS software
there is now mentioning of  "untracked source files" but this should not give any problems.
![untracked source files](https://github.com/Rat-OS/RatOS/assets/17086421/3cb00b1f-5823-4102-8e3f-1629c3347153)

**Comment by miklschmidt** [comment]
For future reference, that error indicates a dying sd card. I'd swap to a new one from a reliable brand (can recommend SanDisk Extreme).
