### ISSUE TITLE
Add Rapido 2 Config

### ISSUE THREAD

**Issue by SirFarquaad** [Rat-Rig/V-CoreOS#116]
### Is your feature request related to a problem? Please describe

Recently received a new ratrig kit which included a rapido 2 hotend. Naively used the default rapido.cfg and the rapido 2 uses a pt1000 thermistor which caused incorrect temperatures for the hotend (~156C unheated) and the reported temperature to decrease when hotend was turned.

### Describe the solution you'd like

Rapido config with the below overrides in printer.cfg appear to be working properly(BTT Octopus V1.1 w/ default wiring). 

[extruder]
sensor_type: PT1000

I kindly suggest copying rapido.cfg and creating a rapidoV2.cfg for this new hotend with proper sensor type to help new folks that are receiving with kits.

### Describe alternatives you've considered

Documenting the behavior/need to override somewhere in the ratrig/ratos docs may be a better alternative

### Additional information

Further tweaks to other hotend variables may be warranted in the future for this V2 rapido vs the V1 version but I haven't completed extensive testing at this point and am overall happy with simple sensor type override and looking to spare others some frustrations with troubleshooting.

**Comment by miklschmidt** [comment]
Closed following 2.1.0-RC1
