### ISSUE TITLE
Add support for raspberry pi 5

### ISSUE THREAD

**Issue by puntodecontrol** [Rat-Rig/V-CoreOS#118]
### Is your feature request related to a problem? Please describe

As the new rasp has got arm8, i cant use it.

### Describe the solution you'd like

Add support for raspberry pi 5

**Comment by miklschmidt** [comment]
Support for Pi 5 is currently not planned, although it probably will happen at some point. It's complicated for multiple reasons. There have been a few users succefully compiling images for the RPi 5 though, please check discord :)

I'm closing this for now, i'll most likely be following MainsailOS' lead.
