### ISSUE TITLE
Octopus max support

### ISSUE THREAD

**Issue by mkljax** [Rat-Rig/V-CoreOS#120]
### What happened

not seeing Octopus Max for a control board in printer setup with the armbian CB1 Ratos V2.0.2

### What did you expect to happen

expected to see Octopus Max EZ as a printer setup option because it is listed on the url https://os.ratrig.com/docs/boards/list

### How to reproduce

login into " http://ratos.local/configure?step=1" and do not see Octopus Max EZ as a printer setup choice.

### Additional information

Tried to do a manual klipper firmware compilation but could not find octopus max ez in the "boards" directory.

**Comment by keyquesttech** [comment]
Did you manage to fix it?

**Comment by mkljax** [comment]
No. It may not be implemented because the CB1 is experimental.

________________________________

**Comment by keyquesttech** [comment]
I managed to do it. Just had to log in to the mainsail GUI and update everything

**Comment by mkljax** [comment]
Did you use the 32bit or 64bit version of armbian?
________________________________

**Comment by mkljax** [comment]
Sorry thought there was a 32bit armbian, its only the Pi that has both.

________________________________

**Comment by mkljax** [comment]
Thx, that got it to populate with the board.
________________________________
