### ISSUE TITLE
Pi 5 Support

### ISSUE THREAD

**Issue by ddellant** [Rat-Rig/V-CoreOS#124]
### Is your feature request related to a problem? Please describe

I tried installing RATOS on a brand new pi5. I was not able to get it to broadcast, this issue is something I have seen with other precompiled images, like the one on the raspberry pi imager. I was able to circumvent this by writing the basic raspberry pi image to the pi and kiauh-ing the rest of the needed software in.

### Describe the solution you'd like

Support for Pi5, or at least some kind of script I can run to install it on a blank linux build!

### Describe alternatives you've considered

I would just run this without RatOS as I am not stranger to klipper, but I was planning on using some of Helge Keck's IDEX features.

### Additional information

Thank you!

**Comment by miklschmidt** [comment]
Pi5 requires Bookworm, we don't support bookworm yet. Making sure every single dependency and implementation detail is stable and working on Bookworm is quite a huge undertaking that doesn't serve any purpose right now. The Pi 5 doesn't really have anything we're missing. It's however missing hardware encoding, which is not nice :(

Bookworm will be supported eventually, but it's not a priority at the moment.
