### ISSUE TITLE
PSA: RatOS already has Beacon installed and will flash it automatically, don't install it again.

### ISSUE THREAD

**Issue by miklschmidt** [Rat-Rig/V-CoreOS#127]
With the release of Beacon TrueZero, a lot of people are running the beacon install scripts on their setups. This is not necessary and breaks the existing beacon installation (as the beacon docs guides you to install it in a different directory, so you end up with 2 copies fighting eachother). All you need to do is make sure your beacon is plugged in, then update RatOS and Beacon through the mainsail machine tab, and RatOS will flash your beacon automatically. If you updated before connecting the beacon and you need to flash it, you can do it manually from the help menu in the configurator.

**Comment by WO1984PR** [comment]
So, when we see the message "beacon v2.0.0-16 > v2.0.0-17" "Update" Ignore it? My current version is "mcu beacon
Version: Beacon 2.1.0"  just from doing all of the other updates on first boot.

**Comment by miklschmidt** [comment]
You should still update it through the update manager :)

**Comment by WO1984PR** [comment]
I am just trying to get my install to work. But, I did the upgrade from this page in the machine.
![updated from](https://github.com/user-attachments/assets/f108fe11-b05a-4905-a5f5-2318e42044b9)
