### ISSUE TITLE
Support for OrangePi cm4 in Ratos 2.1

### ISSUE THREAD

**Issue by cross81** [Rat-Rig/V-CoreOS#132]
### Is your feature request related to a problem? Please describe

I currently run my RatRig with an OrangePi cm4, and it would love to be able to use RatOS again.

### Describe the solution you'd like

Add support for the OrangePi cm4 debian http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi-CM4-1.html to RatOS 2.1

**Comment by miklschmidt** [comment]
Oh they have a raspberry pi OS image. In that case it might be straight forward, i've started a build here: https://github.com/Rat-OS/RatOS/actions/runs/9505229132/job/26199647562

**Comment by miklschmidt** [comment]
It's missing a standard boot/config.txt .. i'll add the [all] sections from the original image and see what happens.

**Comment by miklschmidt** [comment]
Trying again https://github.com/Rat-OS/RatOS/actions/runs/9505585306

**Comment by cross81** [comment]
> It's missing a standard boot/config.txt .. i'll add the [all] sections from the original image and see what happens.

they renamed it  /boot/orangepiEnv.txt
took me a minute to figure that one out when i was setting up a BTT HDMI7

**Comment by miklschmidt** [comment]
@cross81 different file (also wouldn't do anything on raspberry pi os), cmdline.txt is missing too.

**Comment by miklschmidt** [comment]
Here we go again https://github.com/Rat-OS/RatOS/actions/runs/9508255431

**Comment by miklschmidt** [comment]
@cross81 aight... it finished.. Give it a shot! https://github.com/Rat-OS/RatOS/actions/runs/9508255431/artifacts/1600396186

**Comment by cross81** [comment]
Awesome! Thank you! I'll try it out.

**Comment by cross81** [comment]
It works! took me a bit to get a can network set up until I realized that /etc/network/interfaces was missing the line source /etc/network/interfaces.d/*
once I fixed that, everything worked great!

Thank You again

**Comment by miklschmidt** [comment]
I should probably add the interfaces.d/* inclusion, it's been missing for a while (not sure why it's not default in the base image), and since we prefer USB it doesn't impact RatOS otherwise, so i keep forgetting :D

Good to hear though, will include it by default from here on out, at least until we switch to bookworm (unless they follow suit).

**Comment by cross81** [comment]
They already have bookworm images available. :)
