### ISSUE TITLE
Unable quad_gantry_level on prusa configs

### ISSUE THREAD

**Issue by polloperrocampero** [Rat-Rig/V-CoreOS#133]
### What happened

The RatOs.cfg file has quad_gantry_level defined in the prusa configuration, when it is not used on the machine
![Captura de pantalla 2024-06-12 194821](https://github.com/Rat-OS/RatOS/assets/56415026/0c283984-a562-4712-aacf-907f87412682)

### What did you expect to happen

Unable quad_gantry_level in Ratos.cfg for Prusa configs

### How to reproduce

.

**Comment by miklschmidt** [comment]
Thanks for reporting! Apparently copy pasting is hard! 😂 Fixed :)
