### ISSUE TITLE
RTD PT1000 through MAX31865

### ISSUE THREAD

**Issue by konasimakopoulos** [Rat-Rig/V-CoreOS#140]
### Is your feature request related to a problem? Please describe

I am using the BTT EBB42 1.2 toolboard and measuring the hotend temperature using the integrated MAX31865. I run the configure wizard but selecting the PT1000 leads to it trying to measure temperature with the analog pin. This can be fixed manually but ideally it should be automatically generated.

### Describe the solution you'd like

The configurator should support the MAX31865 as a temperature source.

**Comment by miklschmidt** [comment]
> I run the configure wizard but selecting the PT1000 leads to it trying to measure temperature with the analog pin

This is very much on purpose, we don't recommend you use MAX31685. PT1000 works fine as a regular thermistor, many boards have an optional 2200 ohm pulldown you can enable for this purpose.
