### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by 3D-informatik-tienda** [Rat-Rig/V-CoreOS#57]
Good morning, what is the difference between these 2 versions:

RatOS-v2.0.0-beta1.5-bullseye-arm64-lite.img.xz

RatOS-v2.0.0-beta1.5-bullseye-armhf-lite.img.xz

Which one should I use?

**Comment by swilkens** [comment]
64 and 32 bit, otherwise they are the same.

Which board are you planning to use?

**Comment by 3D-informatik-tienda** [comment]
hi, btt octopus v1.1 and btt skr 2

**Comment by miklschmidt** [comment]
If you're using a raspberry pi with less than 1gb memory, go with 32-bit. For further support, it's much quicker if you use discord at https://discord.gg/ratrig.
