### ISSUE TITLE
M600

### ISSUE THREAD

**Issue by hreality** [Rat-Rig/V-CoreOS#58]
SO, long time listener first time caller...
Printed a F-bomb (two color) on the minion..
When it came to the color change it moves to the front of the bed and only about 2mm above the current layer.  This typically wouldnt be an issue but the print is only @6mm in total z.  Suffice to say once the old filament is removed getting the new purge clear is problematic.  But, RAT OS reports this as a pause state rather than any color change... Code clearly identifies an m600 however.

G1 Z1 F12000
;AFTER_LAYER_CHANGE
;1
;COLOR_CHANGE,T0,#46A601
M600
; printing object F_Bomb.stl id:0 copy 3

PrusaSlicer 2.6

Version: v0.11.0-99-g56444815
OS: Raspbian GNU/Linux 10 (buster)
Distro: RatOS v 1.2.4 (buster)
Load: 0.16, Mem: 136.9 MB / 237.9 MB, Temp: 40°C
wlan0 (10.0.0.189) : Bandwidth: 5.8 kB/s , Received: 208.9 MB , Transmitted: 610.4 MB

**Comment by miklschmidt** [comment]
Pausing the print, doing stuff and resuming is how you do color changes in klipper. If you need more space you can just increase the toolheads Z height via the direction controls in mainsail, the printer will resume in the correct position once you hit RESUME :)
