### ISSUE TITLE
WARNING: BED_MESH behavior is changing in RatOS v2.0

### ISSUE THREAD

**Issue by miklschmidt** [Rat-Rig/V-CoreOS#59]
WARNING: the bed_mesh behavior will change when you update RatOS through mainsail. Read more about the new behavior here: https://rat-os.vercel.app/docs/configuration/macros#bed-mesh-calibration

The changes only affect you if you set `variable_calibrate_bed_mesh` to `False`. In which case a mesh will no longer be loaded until you set `variable_bed_mesh_profile` to a bed_mesh profile name. To restore previous behavior, add `variable_bed_mesh_profile: "ratos"` to `[gcode_macro RatOS]` in your printer.cfg.

**Comment by Hueristic** [comment]
Will this be changing to Kamp?
If not is there a diy for Kamp install?

Link not working
https://rat-os.vercel.app/docs/configuration/macros#bed-mesh-calibration
> 404: NOT_FOUND Code: DEPLOYMENT_NOT_FOUND ID: iad1::8mcnr-1681935174516-8b4a0a388869

**Comment by miklschmidt** [comment]
@Hueristic that's because this announcement was during the alpha, only related to alpha release, and was about how RatOS changed it's behavior with loading bed_meshes. Not related to dynamic bed mesh area.

You can use KAMP, it should work without any issues, though you'd want to leave nozzle priming to RatOS. Or you can go for PAM: https://github.com/HelgeKeck/pam
