### ISSUE TITLE
Unable to setup btt-octopus-pro-429

### ISSUE THREAD

**Issue by ghost** [Rat-Rig/V-CoreOS#60]
### What happened

Running http://ratos.local/configure, where I select my MCU as btt-octopus-pro-429, but in printer.cfg the following is selected

[include RatOS/boards/btt-octopus-11/config.cfg]
instead of 
#[include RatOS/boards/btt-octopus-pro-429/config.cfg]

And Mainsail repports that 

Klipper reports: ERROR
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

In the klipper log it reopports 
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'

### What did you expect to happen

I expecteded it to select [include RatOS/boards/btt-octopus-pro-429/config.cfg]

### How to reproduce

Clean setup with new image using "2023-02-12-RatOS-v2.0.0-beta2-raspberry-rpi64.img"
Perform setup for BTT Octopus Pro V1.1

**Comment by miklschmidt** [comment]
Currently the configurator won't make changes to your printer.cfg, that feature is slated for 3.0. I get the confusion though, which is why it's explained in the tips in this section: https://rat-os.vercel.app/docs/configuration#initial-configuration
