### ISSUE TITLE
preheat_extruder variable

### ISSUE THREAD

**Issue by NiiXXiiN** [Rat-Rig/V-CoreOS#70]
### Is your feature request related to a problem? Please describe

Is not a problem just a request.

### Describe the solution you'd like

Add a variable to change the preheat temperature for the extruder.

### Additional information

I'd like to be able to set different temperatures to speed up the start process.

**Comment by miklschmidt** [comment]
Already there: https://os.ratrig.com/docs/configuration/macros#heating
