### ISSUE TITLE
Add support for Voron Revo 

### ISSUE THREAD

**Issue by smolz** [Rat-Rig/V-CoreOS#72]
### Is your feature request related to a problem? Please describe

With support for the Vorons, there should be support for the Revo Voron hotend.

### Describe the solution you'd like

Addition of a hotend option for the Revo Voron

**Comment by miklschmidt** [comment]
There is already support for Revo, the heatsink doesn't change anything :)

**Comment by smolz** [comment]
Ok, found the actually config file. I guess it is just not listed as an option in printer.cfg

**Comment by miklschmidt** [comment]
@smolz you might be on an old version, before it was add: https://github.com/Rat-OS/RatOS-configuration/blob/v2.x/templates/v-core-3-printer.template.cfg#L137
