### ISSUE TITLE
interfaces.d is not sourced in /etc/network/interfaces

### ISSUE THREAD

**Issue by smolz** [Rat-Rig/V-CoreOS#73]
### What happened

In the file `/etc/network/interfaces` should be a statement that sources the files that are in `/etc/network/interfaces.d`.  This is missing which caused me issues when trying to setup the can0 interface.  In the file `/etc/network/interfaces` there should be something like this:

```
# Include files from /etc/network/interfaces.d:
source /etc/network/interfaces.d/*
```

### What did you expect to happen

The include is typically in the interface file, perhaps not in the base image that is used.

### How to reproduce

Add a can0 interface and it will never show up until the file is sourced.

**Comment by miklschmidt** [comment]
Correct, this isn't default in raspberry pi os bullseye, and should be part of any CAN guide out there. RatOS encourages you to use USB.
