### ISSUE TITLE
Config change gives error

### ISSUE THREAD

**Issue by igor72ita** [Rat-Rig/V-CoreOS#75]
### What happened

If I make the setting for motor performance in the printer.cfg for a v-core 3, I get an error.
File contains no section headers.
file: '/home/pi/printer_data/config/printer.cfg', line: 1
'[in'
have three of the same printer on all three the same.

![image](https://user-images.githubusercontent.com/125159944/231290472-2811a6a6-8aeb-4e86-8177-6bcb069b017f.png)
![image](https://user-images.githubusercontent.com/125159944/231290634-8541634e-b674-47b8-a613-da32cbae4bc0.png)

### What did you expect to happen

that the config works

### How to reproduce

just set it up and restart

**Comment by miklschmidt** [comment]
@igor72ita the issue is in your screenshot, there's a `#` in the middle of `i#nclude` on your last line.

**Comment by igor72ita** [comment]
thanks I didn't notice
