### ISSUE TITLE
wlan0 fixed at 192.168.50.1

### ISSUE THREAD

**Issue by ghost** [Rat-Rig/V-CoreOS#77]
### What happened

WiFi IP address and network are fixed to 192.168.50.1 and can't be changed.

### What did you expect to happen

It should log into my WiFi and obtain an IP address from my DHCP server.

### How to reproduce

Go through the normal setup

**Comment by miklschmidt** [comment]
This is incorrect. What you're looking at is the hotspot settings :)

**Comment by ghost** [comment]
Using your configuration tool, I setup my WiFi, and the only related connection that I see is wlan0.  For a hard wired LAN connection I see lan0.  What should I see for my WiFi?

**Comment by miklschmidt** [comment]
@Kaelum i'm sorry i don't understand the question. If the wifi settings you entered were correct, wlan0 would be connected to your wifi and not hosting the RatOS hotspot.

**Comment by miklschmidt** [comment]
You can check the settings written by the RatOS configurator in /boot/ratos-wpa-supplicant.txt

**Comment by ghost** [comment]
Ok, so something was changed to override the /etc/wpa_supplicant/wpa_supplicant.conf file.  The configuration in the /boot/ratos-wpa-supplicant.txt file does not work either.  Here is a scrubbed version of what your tool wrote:

```
network={
        ssid="my-ssid"
        #psk="my-password"
        psk=e12f36ef7e7250c[]snip]1dafea8b19a0
}
```

**Comment by miklschmidt** [comment]
@Kaelum did you use raspberry pi imager instead of following the docs?

**Comment by ghost** [comment]
@miklschmidt nope, I followed the docs exactly.  I don't have the Raspberry Pi Imager installed on any machine.  I did this from my laptop, which has balenaEtcher installed on it.

**Comment by miklschmidt** [comment]
@Kaelum Could you try on a fresh installation? Because you're the only one that i know of with this issue.

**Comment by ghost** [comment]
@miklschmidt I'll try it in a couple hours, after work, and let you know.  I need to backup the changes that I made to the configs, and what I did to setup CAN, before I start.

**Comment by miklschmidt** [comment]
@Kaelum Awesome, please keep it stock until you've verified if wpa-supplicant is working or not. I suspect the CAN changes might've messed up wpa supplicant.

**Comment by ghost** [comment]
@miklschmidt ok, I did a fresh install, with the CAN board is running over USB, and the exact same thing.  wlan0 is not working.  It is advertising the RatOS SSID.

**Comment by miklschmidt** [comment]
Check your router logs, i cannot reproduce it and have no other reports.

**Comment by miklschmidt** [comment]
Which pi model are you using?

**Comment by ghost** [comment]
Raspberry Pi 4B

Ok, I decided to try a simple installation of the Raspberry Pi OS.  I downloaded the Raspberry Pi Imager, flashed a new SD card, started it, fully patched it, and tried setting up the WiFi.  It worked w/o any issues.  I've wasted too much time on this, so I'm just going to drop it and install the vanilla version of Klipper with all the addons.

Best
