### ISSUE TITLE
FIRMWARE_RESTART turns off can0 and doesn't turn it back on

### ISSUE THREAD

**Issue by ghost** [Rat-Rig/V-CoreOS#79]
### What happened

Whenever `FIRMWARE_RESTART` is used, `can0` is brought down, and it is not brought back up.

### What did you expect to happen

`can0` should be brought back up after a short delay, if it was taken down during a `RESTART_FIRMWARE` or for any other reason.

### How to reproduce

1. You will either need to be running CAN, or create a dummy setup, and bring up the `can0` connection.
2. Issue the `FIRMWARE_RESTART` command by any means.
3. `can0` will be down and will not recover.

**Comment by miklschmidt** [comment]
CAN is not officially supported in RatOS, so unfortunately you're on your own with this one. I recommend using USB.

If you find the issue, and there's no consequences from fixing it, let me know.

**Comment by miklschmidt** [comment]
Closing this as there are no plans to officially support CAN.
