### ISSUE TITLE
Beacon support and native adaptive meshing has landed in RatOS

### ISSUE THREAD

**Issue by miklschmidt** [Rat-Rig/V-CoreOS#88]
When you update RatOS in the machine tab RatOS v2 will have full native support for Beacon (single include) and Adaptive Meshing & Priming (see: https://os.ratrig.com/docs/configuration/adaptive-meshing).

IMPORTANT: If you have already installed the Beacon klippy extension, you should delete the beacon-klipper directory and the beacon moonraker.conf entry before updating.

**Comment by Hueristic** [comment]
Sweet, Pam got on my nerves when an update broke it.
