### ISSUE TITLE
4028 fan guide correction

### ISSUE THREAD

**Issue by ghost** [Rat-Rig/V-CoreOS#92]
### Is your feature request related to a problem? Please describe

The danger message can be changed to a mitigation message.  Since the tachometer is using a pull up resistor, if you put a diode inline with the output of the tachometer, with the cathode on the side of the tachometer, then this issue does not exist.  The tachometer will solely pull down through the diode to the input pin, and will be reverse biased if it is above the pull voltage.

### Describe the solution you'd like

Change the danger message to include this work-around, which will allow the fan to be be fully turned off when at 0%.  Also, there is no reason to waster a heater port when a fan port is actually better.  Fan ports should have diodes across them to prevent reverse EMF damage, whereas a heater port may not.  Just make sure that the 4028 fan is not using more current than the fan port is rated for.  Toolhead CAN boards don't have spare heater ports, and the fan port is perfectly fine for this use.  The unused limit switch ports can be used for the PWM & tachometer signals.

### Additional information

On the EBB42 I have the configuration set as:
```
[fan]
enable_pin: toolboard:fan_part_cooling_pin
pin: toolboard:fan_part_cooling_pwm_pin
cycle_time: 0.01 # 100Hz works best for the Protechnic MGT4012WB-W28-C
tachometer_pin: ^toolboard:fan_part_cooling_tach_pin
tachometer_poll_interval: 0.0005 # will support up to a 30.000 RPM fan with 2 pulses per rotation.
```
with these aliases in the `[board_pins btt-ebb42-12]` toolhead section:
```
# fans
  fan_part_cooling_pin=PA0,
  fan_part_cooling_pwm_pin=PB5,
  fan_part_cooling_tach_pin=PB7,
  fan_toolhead_cooling_pin=PA1
```
The cathode of the diode (1N4148 is a good choice) connects directly to the fan, and the anode connects directly to PB7.

**Comment by miklschmidt** [comment]
> The danger message can be changed to a mitigation message. Since the tachometer is using a pull up resistor, if you put a diode inline with the output of the tachometer, with the cathode on the side of the tachometer, then this issue does not exist. The tachometer will solely pull down through the diode to the input pin, and will be reverse biased if it is above the pull voltage.

Too complicated for regular users. However feel free to write about this somewhere if you want, it's good information if you want to teach people how these things work.

> Just make sure that the 4028 fan is not using more current than the fan port is rated for.

Literally none of them do. The lowest spec of fans we recommend are rated at 1.2A and they're 12V. There's no 12V on your toolboard any way.

There's a very limited amount of 24V 4028's available that are fit for the purpose. Simply isn't worth the trouble, the less gotcha's the easier to understand and follow. Remember RatOS is catered towards beginners, the 4028 guide is already bordering on being too complicated for everyone to follow.

Appreciate the suggestion though!

**Comment by miklschmidt** [comment]
Side note: i recommend you just use the pins directly in your printer.cfg, there's no point in overriding the board pin aliases for yourself, they exist exclusively as an abstraction to allow modularity :)
