### ISSUE TITLE
Error loading template 'gcode_macro CALIBRATE_ADAPTIVE_MESH

### ISSUE THREAD

**Issue by PGlyre** [Rat-Rig/V-CoreOS#94]
### What happened

After update  to RatOS v2.x: v2.0.0-73-ga59c4e9 i git this error, 

Error loading template 'gcode_macro CALIBRATE_ADAPTIVE_MESH:gcode': jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.

### What did you expect to happen

Just to rebbor RatOs and work after this

### How to reproduce

I dint know, I just run Update fron Update Manager in RatOS and after restart of Firmware i got this error 

### Additional information

![Udpate v2 x- v2 0 0-73-ga59c4e9](https://github.com/Rat-OS/RatOS/assets/25323238/6468b73b-a8d8-4460-bc53-fd9902b483d9)
[klippy.log](https://github.com/Rat-OS/RatOS/files/11611808/klippy.log)

**Comment by PGlyre** [comment]
I have compared Old with New macros.cfg. unfortunately it's a bit beyond my knowledge to know where or what kind of commando is missing or wrong, but hopefully this will help so I can get my RatOS up and running again.
![ v2 0 0-73-ga59c4e9_compare1](https://github.com/Rat-OS/RatOS/assets/25323238/05421b83-11cd-4f62-ab6c-6a490cabb558)
![ v2 0 0-73-ga59c4e9_compare2](https://github.com/Rat-OS/RatOS/assets/25323238/ea051a3d-444c-4588-9f43-5ae783ba1e69)

**Comment by miklschmidt** [comment]
This should've been fixed shortly after it was introduced. Is this still an issue?

**Comment by PGlyre** [comment]
Yes, it worked just after your reply and I apologize if I missed replying to you promptly
